name: jerelo
description: >
  A minimal, lawful Dart functional toolkit for composing synchronous and
  asynchronous workflows using continuation-passing style (CPS).
version: 1.0.0
repository: https://github.com/prokhor-andrew/jerelo-dart
homepage: https://github.com/prokhor-andrew/jerelo-dart
issue_tracker: https://github.com/prokhor-andrew/jerelo-dart/issues

environment:
  sdk: ^3.9.2

topics:
  - functional-programming
  - monad
  - continuation
  - async

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
