name: jerelo
description: >
  A minimal, lawful Dart functional toolkit for composing synchronous and
  asynchronous workflows using continuation-passing style (CPS).
version: 1.0.3
repository: https://github.com/prokhor-andrew/jerelo-dart
homepage: https://github.com/prokhor-andrew/jerelo-dart
issue_tracker: https://github.com/prokhor-andrew/jerelo-dart/issues
documentation: https://github.com/prokhor-andrew/jerelo-dart/tree/main/documentation

environment:
  sdk: ^3.0.0

topics:
  - functional-programming
  - monad
  - continuation
  - async
  - effects

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dev_dependencies:
  test: ^1.29.0
